/**
 * Connection Design Panel — main orchestrator component.
 *
 * Manages the full workflow: template selection → load input → API analysis →
 * results display → auto-fix recommendations. Mounted as a left-side panel
 * inside StandaloneApp alongside the existing ConnectionLibraryPanel.
 */

import { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { LeftPanelShell } from '@/components/viewer-panels/LeftPanelShell';
import { TemplateGrid } from './TemplateGrid';
import { LoadInputForm } from './LoadInputForm';
import { AnalysisResults } from './AnalysisResults';
import { AutoFixPanel } from './AutoFixPanel';
import type {
  ConnectionTemplate,
  ConnectionDefaults,
  DesignLoads,
  MemberCapacity,
  AnalysisResult,
  AutoFixRecommendation,
  ConnectionGeometry,
  DesignStep,
} from './types';
import { getRecommendedTemplates, detectGeometryType } from './templates';
import { estimateMemberCapacity, getDefaultLoads } from './capacity';
import { createProject, runAnalysis, closeProject, checkApiHealth, exportConnectionIfc, applyTemplate, autoProposeAndApplyTemplate, getProposedTemplates, getTemplateXml, startIdeaApi } from './api-client';
import { ManualTemplateGrid } from './ManualTemplateGrid';
import type { OrientedMemberVectorRow } from '../member-vectors/types';
import { IfcViewerModal } from './IfcViewerModal';
import { ConnectionOptimizer } from './ConnectionOptimizer';
import { StandardizationDashboard } from './StandardizationDashboard';

interface ConnectionDesignPanelProps {
  /** Whether the panel is open. */
  isOpen: boolean;
  /** Called when the user closes the panel. */
  onClose: () => void;
  /** Oriented member rows from the joint solver (bearing + connected members). */
  memberRows: OrientedMemberVectorRow[];
  /** IOM XML string for the current joint (generated by emit-iom.ts). */
  iomXml: string | null;
  /** Reports this panel's current on-screen width (px) to the host. */
  onPanelWidthChange?: (width: number) => void;
  /** Passes the exported connection IFC buffer and node coordinates to the 3D viewer. */
  onLoadConnectionIfc?: (buffer: ArrayBuffer, nodeMm: [number, number, number]) => void;
  /** Called when the user clicks 'Analyze' to signal the host to close conflicting panels. */
  onStartAnalysis?: () => void;
}

/**
 * Generate auto-fix recommendations based on which checks failed.
 * This is a heuristic engine — it inspects the failing checks and suggests
 * parameter changes that would likely resolve them.
 */
function generateRecommendations(
  result: AnalysisResult,
  params: ConnectionDefaults,
): AutoFixRecommendation[] {
  const recs: AutoFixRecommendation[] = [];
  if (result.overallStatus === 'pass') return recs;

  const BOLT_UPGRADE: Record<string, string> = {
    M12: 'M16', M16: 'M20', M20: 'M24', M24: 'M27', M27: 'M30',
  };

  for (const check of result.checks) {
    if (check.status === 'pass') continue;
    const name = check.name.toLowerCase();

    if (name.includes('bolt') || name.includes('bulon')) {
      const next = BOLT_UPGRADE[params.boltDiameter];
      if (next) {
        recs.push({
          description: `Increase bolt diameter from ${params.boltDiameter} to ${next}`,
          descriptionLocal: `Cıvata çapını ${params.boltDiameter}'den ${next}'e çıkarın`,
          parameterKey: 'boltDiameter',
          currentValue: params.boltDiameter,
          recommendedValue: next,
          reason: 'Bolt shear/bearing capacity is exceeded',
          reasonLocal: 'Cıvata kesme/ezilme kapasitesi aşılmış',
          priority: 1,
        });
      }
    }

    if (name.includes('plate') || name.includes('plaka')) {
      const nextThickness = params.plateThicknessMm + 5;
      recs.push({
        description: `Increase plate thickness from ${params.plateThicknessMm}mm to ${nextThickness}mm`,
        descriptionLocal: `Plaka kalınlığını ${params.plateThicknessMm}mm'den ${nextThickness}mm'ye çıkarın`,
        parameterKey: 'plateThicknessMm',
        currentValue: params.plateThicknessMm,
        recommendedValue: nextThickness,
        reason: 'Plate bending/yielding capacity exceeded',
        reasonLocal: 'Plaka eğilme/akma kapasitesi aşılmış',
        priority: 2,
      });
    }

    if (name.includes('weld') || name.includes('kaynak')) {
      const nextWeld = params.weldThicknessMm + 2;
      recs.push({
        description: `Increase weld thickness from ${params.weldThicknessMm}mm to ${nextWeld}mm`,
        descriptionLocal: `Kaynak kalınlığını ${params.weldThicknessMm}mm'den ${nextWeld}mm'ye çıkarın`,
        parameterKey: 'weldThicknessMm',
        currentValue: params.weldThicknessMm,
        recommendedValue: nextWeld,
        reason: 'Weld capacity exceeded',
        reasonLocal: 'Kaynak kapasitesi aşılmış',
        priority: 3,
      });
    }
  }

  // Deduplicate by parameterKey (keep highest priority)
  const seen = new Set<string>();
  return recs
    .sort((a, b) => a.priority - b.priority)
    .filter(r => {
      if (seen.has(r.parameterKey)) return false;
      seen.add(r.parameterKey);
      return true;
    });
}

export function ConnectionDesignPanel({
  isOpen,
  onClose,
  memberRows,
  iomXml,
  onPanelWidthChange,
  onLoadConnectionIfc,
  onStartAnalysis,
}: ConnectionDesignPanelProps) {
  // ── Workflow state machine ──
  const [step, setStep] = useState<DesignStep>('template-select');
  const [designMode, setDesignMode] = useState<'auto' | 'manual'>('auto');
  const [proposedTemplates, setProposedTemplates] = useState<any[]>([]);
  const [isLoadingTemplates, setIsLoadingTemplates] = useState(false);
  const [manualSelectedItem, setManualSelectedItem] = useState<any | null>(null);

  const [selectedTemplate, setSelectedTemplate] = useState<ConnectionTemplate | null>(null);
  const [designLoads, setDesignLoads] = useState<DesignLoads | null>(null);
  const [currentParams, setCurrentParams] = useState<ConnectionDefaults | null>(null);
  const [analysisResult, setAnalysisResult] = useState<AnalysisResult | null>(null);
  const [recommendations, setRecommendations] = useState<AutoFixRecommendation[]>([]);
  const [isFixing, setIsFixing] = useState(false);
  const [isLoading3D, setIsLoading3D] = useState(false);
  const [isDownloadingIfc, setIsDownloadingIfc] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [apiHealthy, setApiHealthy] = useState<boolean | null>(null);
  const [isStartingApi, setIsStartingApi] = useState(false);
  const [activeProjectId, setActiveProjectId] = useState<string | null>(null);
  const [activeConnectionId, setActiveConnectionId] = useState<number | null>(null);
  const [miniIfcBuffer, setMiniIfcBuffer] = useState<ArrayBuffer | null>(null);
  const [isFullScreenMiniViewer, setIsFullScreenMiniViewer] = useState(false);
  const [isOptimizerOpen, setIsOptimizerOpen] = useState(false);
  const [isStandardizationOpen, setIsStandardizationOpen] = useState(false);
  const [importedTemplateXml, setImportedTemplateXml] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // ── Derived data from member selection ──
  const { isReady, members, detectedGeometry } = useMemo(() => {
    if (!memberRows || memberRows.length === 0) return { isReady: false, members: [], detectedGeometry: 'multi-member' as ConnectionGeometry };
    
    const validMembers = memberRows;
    const geometry = detectGeometryType(validMembers);
    
    return {
      isReady: validMembers.length > 0,
      members: validMembers,
      detectedGeometry: geometry
    };
  }, [memberRows]);

  // ── 1. API Health Check ──
  useEffect(() => {
    if (isOpen) {
      checkApiHealth()
        .then(healthy => setApiHealthy(healthy))
        .catch(() => setApiHealthy(false));
    }
  }, [isOpen]);

  const handleStartApi = async () => {
    try {
      setIsStartingApi(true);
      setError(null);
      await startIdeaApi();
      // Poll health check every second for up to 10 seconds
      let attempts = 0;
      const poll = setInterval(async () => {
        attempts++;
        const healthy = await checkApiHealth().catch(() => false);
        if (healthy) {
          setApiHealthy(true);
          setIsStartingApi(false);
          clearInterval(poll);
        } else if (attempts >= 10) {
          setIsStartingApi(false);
          setError("API başlatıldı fakat hala bağlanılamıyor.");
          clearInterval(poll);
        }
      }, 1000);
    } catch (err: any) {
      setIsStartingApi(false);
      setError(err.message || 'API başlatılamadı');
    }
  };

  const memberProfiles = useMemo(
    () => memberRows.map(r => r.profile),
    [memberRows],
  );

  const availableTemplates = useMemo(
    () => getRecommendedTemplates(detectedGeometry, memberProfiles),
    [detectedGeometry, memberProfiles],
  );

  /** Estimate capacity from the first non-bearing beam (the connected member). */
  const memberCapacity: MemberCapacity | null = useMemo(() => {
    const beam = memberRows.find(r => !r.isBearing) ?? memberRows[0];
    if (!beam) return null;
    return estimateMemberCapacity(beam.profile, beam.material, beam.crossSectionArea, beam.iStrongCm4);
  }, [memberRows]);

  // Reset state when panel closes.
  useEffect(() => {
    if (!isOpen) {
      setStep('template-select');
      setSelectedTemplate(null);
      setDesignLoads(null);
      setCurrentParams(null);
      setAnalysisResult(null);
      setError(null);
      setRecommendations([]);
      setManualSelectedItem(null);
      setProposedTemplates([]);
      setDesignMode('auto');
      setIsLoading3D(false);
      setIsFullScreenMiniViewer(false);
      setIsOptimizerOpen(false);
      setMiniIfcBuffer(null);
    }
  }, [isOpen]);

  // Check API health on mount.
  useEffect(() => {
    if (isOpen) {
      void checkApiHealth().then(setApiHealthy);
    }
  }, [isOpen]);

  // ── Handlers ──

  const loadTemplates = useCallback(async () => {
    if (!iomXml || !apiHealthy) return;
    setIsLoadingTemplates(true);
    setError(null);
    try {
      let pid = activeProjectId;
      let cid = activeConnectionId;
      if (!pid || cid == null) {
        const res = await createProject(iomXml);
        pid = res.projectId;
        cid = res.connectionId;
        setActiveProjectId(pid);
        setActiveConnectionId(cid);
      }
      const items = await getProposedTemplates(pid, cid);
      setProposedTemplates(items);
    } catch (err: any) {
      setError(`Şablonlar yüklenemedi: ${err.message}`);
    } finally {
      setIsLoadingTemplates(false);
    }
  }, [iomXml, apiHealthy, activeProjectId, activeConnectionId]);

  const handleTemplateSelect = useCallback((template: ConnectionTemplate) => {
    setSelectedTemplate(template);
    setCurrentParams(template.defaults);
    setStep('load-input');
  }, []);

  const handleManualTemplateSelect = useCallback((item: any) => {
    setManualSelectedItem(item);
    // Create a dummy template to satisfy the UI requirements for step 'load-input'
    const dummyTemplate: ConnectionTemplate = {
      id: item.conDesignItemId,
      name: item.name,
      nameLocal: item.name,
      description: '', 
      descriptionLocal: '', 
      geometry: detectedGeometry, 
      behavior: 'shear', 
      icon: '',
      defaults: { plateThicknessMm: 10, boltDiameter: 'M20', boltGrade: '8.8', boltCount: 4, boltRows: 2, boltCols: 2, weldThicknessMm: 5, weldType: 'fillet' }
    };
    setSelectedTemplate(dummyTemplate);
    setCurrentParams(dummyTemplate.defaults);
    setStep('load-input');
  }, [detectedGeometry]);

  const handleImportTemplate = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = async (evt) => {
      const xml = evt.target?.result as string;
      setImportedTemplateXml(xml);
      setManualSelectedItem(null);
      const dummyTemplate: ConnectionTemplate = {
        id: 'imported',
        name: file.name,
        nameLocal: file.name,
        description: '', 
        descriptionLocal: '', 
        geometry: detectedGeometry, 
        behavior: 'shear', 
        icon: '',
        defaults: { plateThicknessMm: 10, boltDiameter: 'M20', boltGrade: '8.8', boltCount: 4, boltRows: 2, boltCols: 2, weldThicknessMm: 5, weldType: 'fillet' }
      };
      setSelectedTemplate(dummyTemplate);
      setCurrentParams(dummyTemplate.defaults);
      setDesignMode('manual');
      setStep('load-input');
      if (fileInputRef.current) fileInputRef.current.value = '';
    };
    reader.readAsText(file);
  }, [detectedGeometry]);

  const performAnalysis = useCallback(
    async (loads: DesignLoads, params: ConnectionDefaults) => {
      if (!iomXml || !selectedTemplate) return;
      onStartAnalysis?.();
      setStep('analyzing');
      setError(null);
      try {
        let finalResult: AnalysisResult;
        
        const produceMockResult = async (): Promise<AnalysisResult> => {
          await new Promise(r => setTimeout(r, 1200)); // Add a realistic delay
          return {
            overallStatus: loads.V > 200 ? 'fail' : 'pass',
            maxUnityCheck: Math.min(loads.V / 300, 1.4),
            checks: [
              {
                name: 'Cıvatalar (Kesme)',
                unityCheck: Math.min(loads.V / 300, 1.4),
                status: loads.V > 300 ? 'fail' : loads.V > 240 ? 'warning' : 'pass',
                message: loads.V > 300 ? 'Bolt shear capacity exceeded' : 'OK',
              },
              {
                name: 'Plaka (Eğilme)',
                unityCheck: Math.min(loads.M / 150, 1.2),
                status: loads.M > 150 ? 'fail' : loads.M > 120 ? 'warning' : 'pass',
                message: loads.M > 150 ? 'Plate bending exceeded' : 'OK',
              },
              {
                name: 'Kaynak (Kesme)',
                unityCheck: Math.min((loads.V * 0.7) / 250, 1.1),
                status: (loads.V * 0.7) > 250 ? 'fail' : 'pass',
                message: 'OK',
              },
            ],
            timestamp: Date.now(),
          } as AnalysisResult;
        };

        if (apiHealthy) {
          // Close previous project if exists to prevent IDEA StatiCa API lockup
          if (activeProjectId) {
            try {
              await closeProject(activeProjectId);
            } catch (e) {
              console.warn("Failed to close previous project", e);
            }
          }

          // Real API Flow
          const { projectId, connectionId } = await createProject(iomXml);
          setActiveProjectId(projectId);
          setActiveConnectionId(connectionId);
          
          try {
            if (designMode === 'manual' && manualSelectedItem) {
              const xml = await getTemplateXml(manualSelectedItem.conDesignSetId, manualSelectedItem.conDesignItemId);
              await applyTemplate(projectId, connectionId, xml);
            } else if (designMode === 'manual' && importedTemplateXml) {
              await applyTemplate(projectId, connectionId, importedTemplateXml);
            } else {
              // Apply the best fitting template from the API's Connection Library!
              try {
                await autoProposeAndApplyTemplate(projectId, connectionId);
              } catch (err: any) {
                console.warn("Auto propose failed, falling back to dummy fin-plate.contemp", err);
                alert('Şablon bulma başarısız oldu: ' + err.message + '\n\nModel boş kalacağı için Analiz ve IFC dışa aktarımı çalışmayacaktır!');
                // We'll still try to fetch the dummy, but it's likely empty so applyTemplate will fail
                const templateRes = await fetch('/templates/fin-plate.contemp');
                if (templateRes.ok) {
                  const templateXml = await templateRes.text();
                  await applyTemplate(projectId, connectionId, templateXml);
                }
              }
            }
            
            // Wait, update params isn't fully implemented in our backend yet but we would call it here
            // await updateConnectionParams(projectId, connectionId, params);
            finalResult = await runAnalysis(projectId, [connectionId]);
          } catch (e: any) {
            console.error("Real API calculate failed (likely because model has no physical operations/plates yet)", e);
            alert("Analiz Hatası: " + e.message);
            throw e; // rethrow so the step fails instead of proceeding with fake results!
          }
        } else {
          // Simulated Flow for testing UI
          finalResult = await produceMockResult();
        }

        setAnalysisResult(finalResult);
        const recs = generateRecommendations(finalResult, params);
        setRecommendations(recs);
        setStep('results');
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        setError(`Analiz sırasında hata: ${msg}`);
        setStep('load-input');
      }
    },
    [iomXml, selectedTemplate],
  );

  const handleLoadsSubmit = useCallback(
    async (loads: DesignLoads) => {
      setDesignLoads(loads);
      if (currentParams) await performAnalysis(loads, currentParams);
    },
    [currentParams, performAnalysis],
  );

  const handleApplyFix = useCallback(
    async (rec: AutoFixRecommendation) => {
      if (!designLoads || !currentParams) return;
      setIsFixing(true);
      const newParams = { ...currentParams, [rec.parameterKey]: rec.recommendedValue } as unknown as ConnectionDefaults;
      setCurrentParams(newParams);
      await performAnalysis(designLoads, newParams);
      setIsFixing(false);
    },
    [designLoads, currentParams, performAnalysis],
  );

  const handleApplyAll = useCallback(async () => {
    if (!designLoads || !currentParams || recommendations.length === 0) return;
    setIsFixing(true);
    const newParams = { ...currentParams } as Record<string, unknown>;
    for (const rec of recommendations) {
      newParams[rec.parameterKey] = rec.recommendedValue;
    }
    const finalParams = newParams as unknown as ConnectionDefaults;
    setCurrentParams(finalParams);
    await performAnalysis(designLoads, finalParams);
    setIsFixing(false);
  }, [designLoads, currentParams, recommendations, performAnalysis]);

  /** Compute smart default loads from member capacity + template behavior. */
  const smartDefaults: DesignLoads = useMemo(() => {
    if (memberCapacity && selectedTemplate) {
      return getDefaultLoads(memberCapacity, selectedTemplate.behavior);
    }
    return { N: 0, V: 50, M: 0 };
  }, [memberCapacity, selectedTemplate]);

  const handleShowIn3D = useCallback(async () => {
    try {
      setIsLoading3D(true); // Re-using this state for loading indicator
      let buffer: ArrayBuffer;
      if (apiHealthy && activeProjectId && activeConnectionId) {
        buffer = await exportConnectionIfc(activeProjectId, activeConnectionId);
      } else {
        console.warn('API not healthy or IDs missing, simulating IFC export...');
        buffer = new Uint8Array([0]).buffer; // 1-byte mock buffer
      }
      setMiniIfcBuffer(buffer);
      setIsFullScreenMiniViewer(true);
    } catch (e: any) {
      console.error('Show in 3D failed:', e);
      alert('3D model oluşturulamadı. API Hatası: ' + e.message);
      setMiniIfcBuffer(null);
      setIsFullScreenMiniViewer(false);
    } finally {
      setIsLoading3D(false);
    }
  }, [apiHealthy, activeProjectId, activeConnectionId]);

  const handleDownloadIfc = useCallback(async () => {
    setIsDownloadingIfc(true);
    try {
      let buffer: ArrayBuffer;
      if (apiHealthy && activeProjectId && activeConnectionId) {
        // Use real active project if available
        buffer = await exportConnectionIfc(activeProjectId, activeConnectionId);
      } else {
        // Fallback simulated IFC if API is not healthy
        const response = await fetch('/mock-iom.xml'); // We just reuse the xml for testing or something else
        if (!response.ok) throw new Error("Mock file not found");
        buffer = await response.arrayBuffer();
      }
      
      const blob = new Blob([buffer], { type: "application/octet-stream" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = apiHealthy ? "connection_design.ifc" : "mock_connection_design.ifc";
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (e: any) {
      console.error('Download IFC failed:', e);
      alert('IFC İndirme başarısız oldu. API Hatası: ' + e.message);
    } finally {
      setIsDownloadingIfc(false);
    }
  }, [apiHealthy, activeProjectId, activeConnectionId]);

  if (!isOpen) return null;

  return (
    <LeftPanelShell
      title="IDEA Design"
      onClose={onClose}
      defaultWidth={380}
      minWidth={320}
      maxWidth={600}
      defaultCollapsed={false}
      resizable
      onWidthChange={onPanelWidthChange}
    >
      <div className="flex flex-col h-full w-full overflow-y-auto">
        {/* Header Actions */}
        <div className="px-4 py-2 border-b border-border-primary bg-bg-primary flex justify-end">
          <button
            onClick={() => setIsStandardizationOpen(true)}
            className="flex items-center gap-2 text-[11px] font-medium text-brand-secondary hover:text-brand-secondary/80 bg-brand-secondary/10 px-3 py-1.5 rounded-lg transition-colors border border-brand-secondary/20"
          >
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
            </svg>
            Standartlaştırma Özeti
          </button>
        </div>

        {/* ── Progress breadcrumbs ── */}
        <div className="flex items-center gap-1 p-3 text-xs bg-bg-secondary border-b border-border-primary shrink-0">
          {(['template-select', 'load-input', 'results'] as const).map((s, i) => {
            const labels = ['1. Tip Seçimi', '2. Yükler', '3. Sonuçlar'];
            const isCurrent =
              s === step || (s === 'results' && step === 'analyzing');
            return (
              <span key={s} className="flex items-center gap-1">
                {i > 0 && <span className="text-text-secondary">›</span>}
                <span
                  className={`px-2 py-1 rounded transition-colors ${
                    isCurrent
                      ? 'bg-brand-primary text-text-accent font-medium'
                      : 'text-text-secondary'
                  }`}
                >
                  {labels[i]}
                </span>
              </span>
            );
          })}
        </div>

        {/* API health warning */}
        {apiHealthy === false && (
          <div className="m-3 p-3 bg-status-warning/10 border border-status-warning text-status-warning rounded text-xs flex flex-col gap-2">
            <div>
              ⚠️ IDEA StatiCa API bağlantısı kurulamadı. <code className="font-mono">ConnectionRestApi.exe</code> çalıştığından emin olun.
            </div>
            <button
              onClick={handleStartApi}
              disabled={isStartingApi}
              className="self-start px-3 py-1.5 bg-status-warning text-white font-medium rounded hover:bg-status-warning/90 disabled:opacity-50 transition-colors"
            >
              {isStartingApi ? 'Başlatılıyor...' : 'API\'yi Başlat'}
            </button>
          </div>
        )}

        {/* Error banner */}
        {error && (
          <div className="m-3 p-3 bg-status-error/10 border border-status-error text-status-error rounded text-sm">
            {error}
          </div>
        )}

        {/* ── Step 1: Template Selection ── */}
        {step === 'template-select' && (
          <div className="flex flex-col flex-1">
            <div className="flex bg-bg-secondary p-1 mx-4 mt-4 rounded-lg border border-border-primary/50">
              <button
                className={`flex-1 py-1.5 text-xs font-medium rounded-md transition-colors ${
                  designMode === 'auto' ? 'bg-bg-primary text-brand-primary shadow-sm' : 'text-text-secondary hover:text-text-primary'
                }`}
                onClick={() => setDesignMode('auto')}
              >
                Otomatik (Önerilen)
              </button>
              <button
                className={`flex-1 py-1.5 text-xs font-medium rounded-md transition-colors ${
                  designMode === 'manual' ? 'bg-bg-primary text-brand-primary shadow-sm' : 'text-text-secondary hover:text-text-primary'
                }`}
                onClick={() => setDesignMode('manual')}
              >
                Manuel Seçim
              </button>
            </div>

            {designMode === 'auto' ? (
              <TemplateGrid
                templates={availableTemplates}
                onSelect={handleTemplateSelect}
              />
            ) : (
              <div className="flex-1 overflow-y-auto flex flex-col">
                <div className="px-4 py-3 border-b border-border-primary/20 flex justify-between items-center bg-bg-secondary/50">
                  <span className="text-xs font-medium text-text-secondary">Şablon Yükle (.contemp)</span>
                  <button 
                    className="text-xs px-3 py-1.5 bg-brand-primary text-bg-primary hover:bg-brand-primary/90 rounded-md transition-colors flex items-center gap-1.5 font-medium shadow-sm"
                    onClick={() => fileInputRef.current?.click()}
                  >
                    <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" />
                    </svg>
                    İçe Aktar
                  </button>
                  <input 
                    type="file" 
                    ref={fileInputRef}
                    accept=".contemp,.ideacon" 
                    className="hidden" 
                    onChange={handleImportTemplate} 
                  />
                </div>
                {proposedTemplates.length > 0 ? (
                  <ManualTemplateGrid
                    templates={proposedTemplates}
                    onSelect={handleManualTemplateSelect}
                    disabled={isLoadingTemplates}
                  />
                ) : (
                  <div className="flex flex-col items-center justify-center h-48 text-center px-4">
                    <p className="text-sm text-text-secondary mb-4">
                      Bağlantı şablonlarını doğrudan IDEA StatiCa'dan çekmek için butona tıklayın.
                    </p>
                    <button
                      className="px-4 py-2 bg-brand-primary text-bg-primary rounded-lg text-sm font-medium hover:bg-brand-primary/90 disabled:opacity-50"
                      onClick={loadTemplates}
                      disabled={isLoadingTemplates}
                    >
                      {isLoadingTemplates ? 'Şablonlar Yükleniyor...' : 'Şablonları Getir'}
                    </button>
                  </div>
                )}
              </div>
            )}
          </div>
        )}

        {/* ── Step 2: Load Input ── */}
        {step === 'load-input' && selectedTemplate && (
          <LoadInputForm
            defaultLoads={smartDefaults}
            memberCapacity={memberCapacity}
            onSubmit={handleLoadsSubmit}
            onBack={() => setStep('template-select')}
          />
        )}

        {/* ── Step 3a: Analyzing spinner ── */}
        {step === 'analyzing' && (
          <div className="flex flex-col items-center justify-center p-12 gap-4 min-h-[250px]">
            <div className="w-10 h-10 border-4 border-brand-primary border-t-transparent rounded-full animate-spin" />
            <p className="text-text-primary text-sm animate-pulse">
              IDEA StatiCa ile hesaplanıyor...
            </p>
          </div>
        )}

        {/* ── Step 3b: Results + Auto-Fix ── */}
        {step === 'results' && analysisResult && selectedTemplate && currentParams && (
          <div className="flex flex-col pb-6">
            <AnalysisResults
              result={analysisResult}
              params={currentParams}
              templateName={selectedTemplate.nameLocal}
              onNewAnalysis={() => setStep('load-input')}
              onShowIn3D={handleShowIn3D}
              isLoading3D={isLoading3D}
              onDownloadIfc={handleDownloadIfc}
              isDownloadingIfc={isDownloadingIfc}
              onOptimize={() => setIsOptimizerOpen(true)}
            />
            {recommendations.length > 0 && (
              <div className="px-4">
                <AutoFixPanel
                  recommendations={recommendations}
                  onApplyFix={handleApplyFix}
                  onApplyAll={handleApplyAll}
                  isAnalyzing={isFixing}
                />
              </div>
            )}
          </div>
        )}
      </div>

      {/* Full Screen Modal for Mini Viewer */}
      {isFullScreenMiniViewer && miniIfcBuffer && (
        <IfcViewerModal
          buffer={miniIfcBuffer}
          onClose={() => setIsFullScreenMiniViewer(false)}
        />
      )}

      {/* Optimizer Modal */}
      {isOptimizerOpen && activeProjectId && activeConnectionId && (
        <ConnectionOptimizer
          projectId={activeProjectId}
          connectionId={activeConnectionId}
          onClose={() => setIsOptimizerOpen(false)}
        />
      )}

      {/* Standardization Dashboard Modal */}
      {isStandardizationOpen && (
        <StandardizationDashboard
          onClose={() => setIsStandardizationOpen(false)}
        />
      )}
    </LeftPanelShell>
  );
}
